sudo: required
language: java
jdk: openjdk8

service:
  docker

script:
  - ./mvnw clean install -B


after_success:
  - docker build -t $IMAGE_NAME:$COMMIT .
  - docker tag $IMAGE_NAME:$COMMIT $IMAGE_NAME:$TAG

