sudo: required
language: java
jdk: openjdk8

service:
  docker

env:
 global:
   - COMMIT=${TRAVIS_COMMIT::7}

script:
  - ./mvnw clean install -B


after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS --password-stdin
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
  - export IMAGE_NAME=alexjkd/cicd-demo
  - docker build -t $IMAGE_NAME:$COMMIT .
  - docker tag $IMAGE_NAME:$COMMIT $IMAGE_NAME:$TAG
  - docker push $IMAGE_NAME
  
deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: fw-aws
